/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.RenamedCascadingOption;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RenamedOption
 */
public class RenamedOptionTest {
    private final RenamedOption model = new RenamedOption();

    /**
     * Model tests for RenamedOption
     */
    @Test
    public void testRenamedOption() {
        // TODO: test RenamedOption
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

    /**
     * Test the property 'newValue'
     */
    @Test
    public void newValueTest() {
        // TODO: test newValue
    }

    /**
     * Test the property 'cascadingOptions'
     */
    @Test
    public void cascadingOptionsTest() {
        // TODO: test cascadingOptions
    }

}
