/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.openapitools.client.model.IssueLinkType;
import org.openapitools.client.model.LinkedIssue;

/**
 * Details of a link between issues.
 */
@ApiModel(description = "Details of a link between issues.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2021-04-16T00:02:29.270017+09:00[Asia/Seoul]")
public class IssueLink {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SELF = "self";
  @SerializedName(SERIALIZED_NAME_SELF)
  private URI self;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private IssueLinkType type = null;

  public static final String SERIALIZED_NAME_INWARD_ISSUE = "inwardIssue";
  @SerializedName(SERIALIZED_NAME_INWARD_ISSUE)
  private LinkedIssue inwardIssue = null;

  public static final String SERIALIZED_NAME_OUTWARD_ISSUE = "outwardIssue";
  @SerializedName(SERIALIZED_NAME_OUTWARD_ISSUE)
  private LinkedIssue outwardIssue = null;


   /**
   * The ID of the issue link.
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the issue link.")

  public String getId() {
    return id;
  }




   /**
   * The URL of the issue link.
   * @return self
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URL of the issue link.")

  public URI getSelf() {
    return self;
  }




  public IssueLink type(IssueLinkType type) {
    
    this.type = type;
    return this;
  }

   /**
   * The type of link between the issues.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The type of link between the issues.")

  public IssueLinkType getType() {
    return type;
  }


  public void setType(IssueLinkType type) {
    this.type = type;
  }


  public IssueLink inwardIssue(LinkedIssue inwardIssue) {
    
    this.inwardIssue = inwardIssue;
    return this;
  }

   /**
   * The issue the link joins to.
   * @return inwardIssue
  **/
  @ApiModelProperty(required = true, value = "The issue the link joins to.")

  public LinkedIssue getInwardIssue() {
    return inwardIssue;
  }


  public void setInwardIssue(LinkedIssue inwardIssue) {
    this.inwardIssue = inwardIssue;
  }


  public IssueLink outwardIssue(LinkedIssue outwardIssue) {
    
    this.outwardIssue = outwardIssue;
    return this;
  }

   /**
   * The issue the link originates from.
   * @return outwardIssue
  **/
  @ApiModelProperty(required = true, value = "The issue the link originates from.")

  public LinkedIssue getOutwardIssue() {
    return outwardIssue;
  }


  public void setOutwardIssue(LinkedIssue outwardIssue) {
    this.outwardIssue = outwardIssue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IssueLink issueLink = (IssueLink) o;
    return Objects.equals(this.id, issueLink.id) &&
        Objects.equals(this.self, issueLink.self) &&
        Objects.equals(this.type, issueLink.type) &&
        Objects.equals(this.inwardIssue, issueLink.inwardIssue) &&
        Objects.equals(this.outwardIssue, issueLink.outwardIssue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, self, type, inwardIssue, outwardIssue);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IssueLink {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    inwardIssue: ").append(toIndentedString(inwardIssue)).append("\n");
    sb.append("    outwardIssue: ").append(toIndentedString(outwardIssue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

